import antfu from '@antfu/eslint-config'
import preflightVueA11y from '@victortolbert/preflight/vue-a11y'
import pluginCasePolice from 'eslint-plugin-case-police'

// Mirrors the uxlab config (ADR-0009 / ADR-0014 there) minus the Nuxt layer.
export default antfu(
  {
    type: 'app',
    formatters: {
      css: false,
      html: true,
      markdown: false,
    },
    vue: {
      a11y: true,
      overrides: {
        ...preflightVueA11y,
        'vue/custom-event-name-casing': 'off',
        'vue/one-component-per-file': 'off',
        'vue/no-irregular-whitespace': 'off',
        'vue/no-required-prop-with-default': 'off',
        'vue/no-side-effects-in-computed-properties': 'off',
        'vue/no-unused-refs': 'off',
        'vue/no-template-shadow': 'off',
        // Inertia's useForm() objects are meant to be mutated; shared field
        // components bind straight to them. Reassigning the prop stays an error.
        'vue/no-mutating-props': ['error', { shallowOnly: true }],
        'vue/block-order': ['error', {
          order: ['template', 'style', 'script'],
        }],
        'vue/max-attributes-per-line': ['error', {
          singleline: { max: 2 },
          multiline: { max: 1 },
        }],
        'vue/component-name-in-template-casing': ['error', 'PascalCase', {
          registeredComponentsOnly: false,
          ignores: [],
        }],
      },
    },
    pnpm: false,
    typescript: true,
    stylistic: {
      indent: 2,
      semi: false,
      quotes: 'single',
    },
    ignores: [
      '**/build/**',
      '**/public/**',
      '**/dist/**',
      '**/vendor/**',
      '**/storage/**',
      '**/bootstrap/cache/**',
      '**/.agents/**',
      '**/.ai/**',
      '**/.claude/**',
      '**/.cursor/**',
      '**/.github/**',
      '**/.junie/**',
      '**/.vscode/**',
      // Generated by Wayfinder — regenerated on every build, never hand-edited.
      'resources/js/actions/**',
      'resources/js/routes/**',
      'resources/js/wayfinder/**',
      '**/*.md',
      'scripts/**',
      // Laravel-owned files keep Laravel's formatting.
      'vite.config.ts',
    ],
  },
  {
    rules: {
      'no-console': 'off',
      'unused-imports/no-unused-vars': 'off',
      'node/no-process-env': ['error'],
      'node/prefer-global/process': ['off'],
      'ts/no-redeclare': 'off',
      'ts/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      'unicorn/filename-case': ['error', {
        case: 'kebabCase',
        ignore: ['CLAUDE.md', 'AGENTS.md', 'README.md'],
      }],
    },
  },
  {
    plugins: {
      'case-police': pluginCasePolice,
    },
    rules: {
      // Wayfinder import paths mirror PHP namespaces (App/Http/Controllers).
      // @case-police-ignore http
      'case-police/string-check': ['warn', { ignore: ['http'] }],
    },
  },
)
